
cd ../../..

set LDSCRIPT=config/stm32f4ems/STM32F407xG.ld

set PROJECT_BOARD=ME7_Assembled
set PROJECT_CPU=ARCH_STM32F4
set EXTRA_PARAMS=-DDUMMY ^
 -DEFI_ENABLE_ASSERTS=FALSE ^
 -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_TRACE=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE
set DEBUG_LEVEL_OPT="-O2"

call config/boards/common_make.bat

call config/boards/clean_env_variables.bat